### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by Loptt** [codyvi/WebDevClass#1]
Hello. I'm trying to use your code from Lab 1 to create my own resume. Nonetheless, I am unable to insert my own information into the website. So you plan on supporting an HTML templating functionality in the near future? So that I can use your open source code in my own project. Thanks!

**Comment by codyvi** [comment]
Hi Carlos! Right now this template only has the purpose of using the correct tags and making an HTML file that when opened you could visualize a form of Resume if you want you could clone the repo and change all my stuff and replace it with yours.

**Comment by Loptt** [comment]
Thanks! Will do!
